-- LunaTrade initial schema (PostgreSQL). Generated by `python -m lunatrade db sql`.

CREATE TABLE agent_events (
	id VARCHAR(40) NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	topic VARCHAR(60), 
	source VARCHAR(60), 
	correlation_id VARCHAR(60), 
	payload JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_agent_events_correlation_id ON agent_events (correlation_id);

CREATE INDEX ix_agent_events_topic ON agent_events (topic);

CREATE INDEX ix_agent_events_ts ON agent_events (ts);

CREATE TABLE agent_health (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	worker_id VARCHAR(80), 
	status VARCHAR(12), 
	runs INTEGER, 
	errors INTEGER, 
	avg_latency_ms FLOAT, 
	reason TEXT, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_agent_health_ts ON agent_health (ts);

CREATE INDEX ix_agent_health_worker_id ON agent_health (worker_id);

CREATE TABLE agents (
	id VARCHAR(80) NOT NULL, 
	name VARCHAR(80), 
	family VARCHAR(30), 
	phase INTEGER, 
	kind VARCHAR(20), 
	params JSON, 
	status VARCHAR(20), 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_agents_family ON agents (family);

CREATE TABLE approvals (
	proposal_id VARCHAR(40) NOT NULL, 
	requested_at TIMESTAMP WITHOUT TIME ZONE, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(12), 
	decided_by VARCHAR(60), 
	decided_at TIMESTAMP WITHOUT TIME ZONE, 
	summary TEXT, 
	PRIMARY KEY (proposal_id)
);

CREATE TABLE backtests (
	id VARCHAR(40) NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	name VARCHAR(80), 
	config JSON, 
	metrics JSON, 
	equity_curve JSON, 
	PRIMARY KEY (id)
);

CREATE TABLE fills (
	id SERIAL NOT NULL, 
	client_order_id VARCHAR(40), 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	symbol VARCHAR(30), 
	side VARCHAR(4), 
	qty FLOAT, 
	price FLOAT, 
	fee FLOAT, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_fills_client_order_id ON fills (client_order_id);

CREATE TABLE knowledge (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	kind VARCHAR(30), 
	title VARCHAR(200), 
	body TEXT, 
	tags JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_knowledge_kind ON knowledge (kind);

CREATE TABLE market_data (
	symbol VARCHAR(30) NOT NULL, 
	interval VARCHAR(5) NOT NULL, 
	open_time BIGINT NOT NULL, 
	open FLOAT, 
	high FLOAT, 
	low FLOAT, 
	close FLOAT, 
	volume FLOAT, 
	quote_volume FLOAT, 
	trades FLOAT, 
	taker_buy_base FLOAT, 
	PRIMARY KEY (symbol, interval, open_time)
);

CREATE TABLE market_snapshots (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	symbol VARCHAR(30), 
	price FLOAT, 
	spread_bps FLOAT, 
	regime VARCHAR(80), 
	assessment JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_market_snapshots_symbol ON market_snapshots (symbol);

CREATE INDEX ix_market_snapshots_ts ON market_snapshots (ts);

CREATE TABLE model_versions (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	component VARCHAR(40), 
	version VARCHAR(40), 
	params JSON, 
	notes TEXT, 
	PRIMARY KEY (id)
);

CREATE TABLE news_events (
	id VARCHAR(40) NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	source VARCHAR(40), 
	title TEXT, 
	url TEXT, 
	assets JSON, 
	event_type VARCHAR(30), 
	sentiment FLOAT, 
	novelty FLOAT, 
	credibility FLOAT, 
	impact FLOAT, 
	data JSON, 
	ret_1h FLOAT, 
	ret_4h FLOAT, 
	ret_24h FLOAT, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_news_events_event_type ON news_events (event_type);

CREATE INDEX ix_news_events_ts ON news_events (ts);

CREATE TABLE orders (
	client_order_id VARCHAR(40) NOT NULL, 
	proposal_id VARCHAR(40), 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	symbol VARCHAR(30), 
	side VARCHAR(4), 
	order_type VARCHAR(10), 
	broker VARCHAR(20), 
	mode VARCHAR(10), 
	status VARCHAR(20), 
	requested_qty FLOAT, 
	requested_notional FLOAT, 
	filled_qty FLOAT, 
	avg_price FLOAT, 
	fee FLOAT, 
	reference_price FLOAT, 
	slippage_bps FLOAT, 
	exchange_order_id VARCHAR(60), 
	error TEXT, 
	history JSON, 
	PRIMARY KEY (client_order_id)
);

CREATE INDEX ix_orders_created_at ON orders (created_at);

CREATE INDEX ix_orders_proposal_id ON orders (proposal_id);

CREATE INDEX ix_orders_status ON orders (status);

CREATE INDEX ix_orders_symbol ON orders (symbol);

CREATE TABLE portfolio_snapshots (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	equity FLOAT, 
	cash FLOAT, 
	exposure FLOAT, 
	drawdown FLOAT, 
	mode VARCHAR(10), 
	data JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_portfolio_snapshots_ts ON portfolio_snapshots (ts);

CREATE TABLE positions (
	symbol VARCHAR(30) NOT NULL, 
	qty FLOAT, 
	entry FLOAT, 
	stop FLOAT, 
	target FLOAT, 
	opened_at VARCHAR(40), 
	proposal_id VARCHAR(40), 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (symbol)
);

CREATE TABLE risk_decisions (
	id SERIAL NOT NULL, 
	proposal_id VARCHAR(40), 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	approved BOOLEAN, 
	approved_notional FLOAT, 
	requested_notional FLOAT, 
	checks JSON, 
	reasons JSON, 
	devils_advocate JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_risk_decisions_proposal_id ON risk_decisions (proposal_id);

CREATE TABLE sentiment_events (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	asset VARCHAR(20), 
	community VARCHAR(40), 
	sentiment FLOAT, 
	classification VARCHAR(30), 
	posts INTEGER, 
	data JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_sentiment_events_ts ON sentiment_events (ts);

CREATE TABLE signals (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	cycle_id VARCHAR(40), 
	worker_id VARCHAR(80), 
	family VARCHAR(30), 
	symbol VARCHAR(30), 
	direction VARCHAR(8), 
	confidence FLOAT, 
	setup VARCHAR(60), 
	expected_move FLOAT, 
	horizon VARCHAR(12), 
	evidence JSON, 
	context JSON, 
	price FLOAT, 
	outcome_return FLOAT, 
	evaluated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_signals_cycle_id ON signals (cycle_id);

CREATE INDEX ix_signals_eval ON signals (evaluated_at, ts);

CREATE INDEX ix_signals_symbol ON signals (symbol);

CREATE INDEX ix_signals_ts ON signals (ts);

CREATE INDEX ix_signals_worker_id ON signals (worker_id);

CREATE TABLE strategy_performance (
	strategy VARCHAR(40) NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	samples INTEGER, 
	hit_rate FLOAT, 
	recent_hit_rate FLOAT, 
	signal_edge FLOAT, 
	weight FLOAT, 
	trades INTEGER, 
	win_rate FLOAT, 
	avg_win FLOAT, 
	avg_loss FLOAT, 
	expectancy FLOAT, 
	profit_factor FLOAT, 
	sharpe FLOAT, 
	sortino FLOAT, 
	max_drawdown FLOAT, 
	avg_holding_bars FLOAT, 
	avg_slippage_bps FLOAT, 
	by_regime JSON, 
	by_asset JSON, 
	PRIMARY KEY (strategy)
);

CREATE TABLE system_alerts (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	level VARCHAR(10), 
	source VARCHAR(40), 
	message TEXT, 
	data JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_system_alerts_ts ON system_alerts (ts);

CREATE TABLE trade_outcomes (
	id SERIAL NOT NULL, 
	proposal_id VARCHAR(40), 
	symbol VARCHAR(30), 
	opened_at VARCHAR(40), 
	closed_at VARCHAR(40), 
	entry FLOAT, 
	exit FLOAT, 
	qty FLOAT, 
	pnl FLOAT, 
	return_pct FLOAT, 
	r_multiple FLOAT, 
	reason VARCHAR(30), 
	bars_held INTEGER, 
	conviction FLOAT, 
	regime VARCHAR(30), 
	supporting JSON, 
	review JSON, 
	mode VARCHAR(10), 
	PRIMARY KEY (id)
);

CREATE INDEX ix_trade_outcomes_proposal_id ON trade_outcomes (proposal_id);

CREATE INDEX ix_trade_outcomes_symbol ON trade_outcomes (symbol);

CREATE TABLE trade_proposals (
	id VARCHAR(40) NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	symbol VARCHAR(30), 
	direction VARCHAR(8), 
	action VARCHAR(10), 
	conviction FLOAT, 
	win_probability FLOAT, 
	entry FLOAT, 
	stop FLOAT, 
	target FLOAT, 
	requested_notional FLOAT, 
	regime VARCHAR(30), 
	rationale TEXT, 
	status VARCHAR(20), 
	data JSON, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_trade_proposals_status ON trade_proposals (status);

CREATE INDEX ix_trade_proposals_symbol ON trade_proposals (symbol);

CREATE INDEX ix_trade_proposals_ts ON trade_proposals (ts);

CREATE TABLE whale_events (
	id SERIAL NOT NULL, 
	ts TIMESTAMP WITHOUT TIME ZONE, 
	asset VARCHAR(20), 
	amount_usd FLOAT, 
	from_type VARCHAR(20), 
	to_type VARCHAR(20), 
	kind VARCHAR(30), 
	bias FLOAT, 
	tx_hash VARCHAR(120), 
	PRIMARY KEY (id)
);

CREATE INDEX ix_whale_events_ts ON whale_events (ts);

